[package]
name = "task_zero"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
serde = "1.0.228"
serde_json = "1.0.145"
chrono = "0.4.42"
